name: build

on: 
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v4

      - name: Build snaps
        id: build-snapcraft
        uses: canonical/action-build@v1
        with:
          snapcraft-channel: latest/edge/pr-5233

      - name: Upload snapcraft snap
        uses: actions/upload-artifact@v4
        with:
          name: snap
          path: "**/*.snap"
